version: "3.7"

services:
  php:
    build:
      args:
        user: app
        uid: 1000
      context: .
      dockerfile: docker/php/Dockerfile
    image: php
    container_name: php
    restart: unless-stopped
    working_dir: /var/www/back
    volumes:
      - ./:/var/www/back
    extra_hosts:
        - "host.docker.internal:host-gateway"
    networks:
      - project_mayhem

  worker:
      build:
          args:
              user: app
              uid: 1000
          context: .
          dockerfile: docker/php/Dockerfile
      image: php
      container_name: worker
      command: bash -c "php artisan queue:work --tries=3"
      restart: unless-stopped
      working_dir: /var/www/back
      volumes:
          - ./:/var/www/back
      extra_hosts:
          - "host.docker.internal:host-gateway"
      networks:
          - project_mayhem

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - project_mayhem

  test_db:
      image: mysql:8.0
      container_name: test_db
      restart: unless-stopped
      environment:
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_PASSWORD: ${DB_PASSWORD}
          MYSQL_USER: ${DB_USERNAME}
          SERVICE_TAGS: dev
          SERVICE_NAME: mysql
      volumes:
          - ./docker/mysql/test_data:/var/lib/mysql
      ports:
          - "3307:3306"
      networks:
          - project_mayhem

  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:8000" # Laravel port
    volumes:
      - ./:/var/www/back
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - project_mayhem
networks:
  project_mayhem:
    driver: bridge
